import mongoose from "mongoose";
//booking should shows clients details so we have to pass them
//autoGenerateId, email, status (“pending”|”confirmed”|”cancelled”), reason(“reason for the status”) , start, end, roomId

const bookingSchema = new mongoose.Schema({

  bookingId:{                //cant use DB id ,should autogeneratedId,normally not use first number for businesses
    type: Number,
    required: true,
    unique: true
  },
  roomId:{
    type: Number,
    required: true
  },
  email:{
    type: String,
    required: true
  },
  status:{
    type: String,
    required: true,
    default: "pending"
  },
  reason:{            //(“reason for the status”)
    type: String,
    default: ""
  },
  start:{                 //if you want to date no default = date.now
    type: Date,
    required: true
  },
  end:{
    type: Date,
    required: true
  },
  notes: {                 //for like bill,invoice,purchase issues or addition infor
    type: String,
    default: ""
  },
  timestamp:{
    type: Date,
    default: Date.now
  }
})

const Booking = mongoose.model("Bookings",bookingSchema)


export default Booking;